<script setup lang="ts">
import { onMounted, ref } from "vue"
import { apiRequest } from "../../api"
import AdminHeader from "../../components/AdminHeader.vue"

interface Event { id: number; created_at: string; actor_username: string; action: string; target_type: string; target_label: string }
const events = ref<Event[]>([]); const page = ref(1); const total = ref(0); const action = ref(""); const actor = ref(""); const fromAt = ref(""); const toAt = ref("")
const labels: Record<string, string> = { "role.created": "Role created", "role.updated": "Role updated", "role.deleted": "Role deleted", "user.created": "User created", "user.updated": "User updated", "user.deleted": "User deleted", "user.role_changed": "User role changed", "user.source_access_changed": "User source access changed", "user.status_changed": "User status changed", "user.password_changed": "User password changed", "user.require_password_change_changed": "Password-change requirement changed", "source.created": "Source created", "source.updated": "Source updated", "source.deleted": "Source deleted", "scan.started": "Scan started", "scan.pause_requested": "Scan pause requested", "scan.resume_requested": "Scan resume requested", "scan.cancel_requested": "Scan cancel requested", "backup.started": "Backup started", "backup.completed": "Backup completed", "backup.failed": "Backup failed", "backup.restore_started": "Database restore started", "backup.restore_completed": "Database restore completed", "backup.restore_failed": "Database restore failed", "metadata.created": "Metadata created", "metadata.updated": "Metadata updated", "metadata.deleted": "Metadata deleted", "tag.created": "Tag created", "tag.updated": "Tag updated", "tag.deleted": "Tag deleted", "folder_tag_rule.created": "Folder tag rule created", "folder_tag_rule.updated": "Folder tag rule updated", "folder_tag_rule.deleted": "Folder tag rule deleted", "automatic_tag_rule.created": "Automatic tag rule created", "automatic_tag_rule.updated": "Automatic tag rule updated", "automatic_tag_rule.deleted": "Automatic tag rule deleted", "model_tag.added": "Model tag added", "model_tag.removed": "Model tag removed", "folder_name_regex_tag_rule.created": "Folder name rule created", "folder_name_regex_tag_rule.updated": "Folder name rule updated", "folder_name_regex_tag_rule.deleted": "Folder name rule deleted" }
function iso(value: string) { return value ? new Date(value).toISOString() : "" }
async function load(reset = false) { if (reset) page.value = 1; const q = new URLSearchParams({ page: String(page.value), page_size: "25" }); if (action.value) q.set("action", action.value); if (actor.value) q.set("actor", actor.value); if (fromAt.value) q.set("from_at", iso(fromAt.value)); if (toAt.value) q.set("to_at", iso(toAt.value)); const data = await apiRequest<{items: Event[]; total: number}>(`/api/admin/audit-events?${q}`); events.value = reset ? data.items : [...events.value, ...data.items]; total.value = data.total }
onMounted(() => load(true))
function reset() { action.value = ""; actor.value = ""; fromAt.value = ""; toAt.value = ""; void load(true) }
</script>
<template><main class="admin-shell"><AdminHeader title="Audit log" /><p class="admin-intro">Review security and administration changes.</p><section class="panel"><h2>Filter audit events</h2><form class="audit-filters" @submit.prevent="load(true)"><label>Action<select v-model="action"><option value="">All actions</option><option v-for="(label, key) in labels" :key="key" :value="key">{{ label }}</option></select></label><label>Actor<input v-model="actor" placeholder="Search username"></label><label>From<input v-model="fromAt" type="datetime-local"></label><label>To<input v-model="toAt" type="datetime-local"></label><div class="row-actions"><button class="primary-button">Apply filters</button><button class="secondary-button" type="button" @click="reset">Reset</button></div></form></section><section class="panel"><p v-if="!events.length" class="muted">No audit events match these filters.</p><div v-else class="audit-table"><div class="audit-head"><span>Timestamp</span><span>Actor</span><span>Event</span><span>Target</span></div><article v-for="event in events" :key="event.id" class="audit-row"><span>{{ new Date(event.created_at).toLocaleString() }}</span><strong>{{ event.actor_username }}</strong><span>{{ labels[event.action] ?? event.action.replaceAll('.', ' ') }}</span><span>{{ event.target_type }} · {{ event.target_label }}</span></article></div><button v-if="events.length < total" class="secondary-button load-more" @click="page++; load()">Load more</button></section></main></template>
<style scoped>.audit-filters,.audit-table{display:grid;gap:1rem}.audit-filters{grid-template-columns:repeat(4,minmax(0,1fr));align-items:end}.audit-filters label{display:grid;gap:.4rem}.audit-filters input,.audit-filters select{min-height:2.5rem}.audit-head,.audit-row{display:grid;grid-template-columns:1.2fr 1fr 1.5fr 1.5fr;gap:1rem;padding:.75rem}.audit-head{color:#94a3b8;font-size:.85rem}.audit-row{border-top:1px solid #28364b}.audit-row:hover{background:#162033}.load-more{margin-top:1rem}@media(max-width:700px){.audit-filters{grid-template-columns:1fr}.audit-head{display:none}.audit-row{grid-template-columns:1fr}.audit-row span::before{display:block;color:#94a3b8;font-size:.75rem}}</style>
