<script setup lang="ts">
import { computed, ref, watch } from "vue"
import { ApiError, apiRequest } from "../../api"

const props = defineProps<{ profileId: number | null }>()
type Alias = { id: number; alias: string; normalized_alias: string }
type Profile = { id: number; display_name: string; normalized_name: string; description: string | null; aliases: Alias[] }
type Preview = { favorite_count: number; duplicate_favorite_count: number; duplicate_link_ids: number[]; link_conflicts: Array<{ source_link_id: number; label: string }>; artwork_conflict: boolean }
const profile = ref<Profile | null>(null); const name = ref(""); const description = ref(""); const alias = ref(""); const mergeSourceId = ref<number | null>(null); const profiles = ref<Profile[]>([]); const preview = ref<Preview | null>(null); const error = ref("")
const candidates = computed(() => profiles.value.filter(item => item.id !== props.profileId))
async function load() { profile.value = null; preview.value = null; alias.value = ""; if (!props.profileId) return; try { const all = await apiRequest<Profile[]>("/api/admin/creator-profiles"); profiles.value = all; profile.value = all.find(item => item.id === props.profileId) ?? null; name.value = profile.value?.display_name ?? ""; description.value = profile.value?.description ?? "" } catch (cause) { error.value = cause instanceof ApiError ? cause.message : "Unable to load creator profile" } }
async function save() { if (!profile.value) return; await apiRequest(`/api/admin/creator-profiles/${profile.value.id}`, { method: "PUT", body: JSON.stringify({ display_name: name.value, description: description.value || null }) }); await load() }
async function addAlias() { if (!profile.value || !alias.value.trim()) return; await apiRequest(`/api/admin/creator-profiles/${profile.value.id}/aliases`, { method: "POST", body: JSON.stringify({ alias: alias.value }) }); await load() }
async function removeAlias(item: Alias) { if (!profile.value) return; await apiRequest(`/api/admin/creator-profiles/${profile.value.id}/aliases/${item.id}`, { method: "DELETE" }); await load() }
async function getPreview() { if (!profile.value || !mergeSourceId.value) return; preview.value = await apiRequest<Preview>("/api/admin/creator-profiles/merge/preview", { method: "POST", body: JSON.stringify({ target_profile_id: profile.value.id, source_profile_ids: [mergeSourceId.value] }) }) }
async function applyMerge() { if (!profile.value || !mergeSourceId.value || !preview.value) return; const artwork = preview.value.artwork_conflict ? prompt(`Artwork: target or source:${mergeSourceId.value}`, "target") : null; if (preview.value.artwork_conflict && artwork !== "target" && artwork !== `source:${mergeSourceId.value}`) return; const link_resolutions = preview.value.link_conflicts.map(item => ({ source_link_id: item.source_link_id, action: confirm(`Keep source link ${item.label}?`) ? "keep_source" : "keep_target" })); await apiRequest("/api/admin/creator-profiles/merge", { method: "POST", body: JSON.stringify({ target_profile_id: profile.value.id, source_profile_ids: [mergeSourceId.value], artwork_resolution: artwork, link_resolutions }) }); await load() }
watch(() => props.profileId, () => void load(), { immediate: true })
</script>
<template><section v-if="profile" class="creator-metadata-section"><h4>Profile</h4><p v-if="error" class="form-error">{{ error }}</p><form class="source-form" @submit.prevent="save"><label>Display name<input v-model="name" required></label><label>Description<textarea v-model="description" /></label><button class="primary-button">Save profile</button></form><h4>Aliases</h4><ul><li v-for="item in profile.aliases" :key="item.id">{{ item.alias }} <button v-if="item.normalized_alias !== profile.normalized_name" class="text-button" @click="removeAlias(item)">Remove</button></li></ul><form @submit.prevent="addAlias"><input v-model="alias" placeholder="Add alias"><button>Add alias</button></form><h4>Merge</h4><select v-model.number="mergeSourceId"><option :value="null">Choose source profile</option><option v-for="item in candidates" :key="item.id" :value="item.id">{{ item.display_name }}</option></select><button :disabled="!mergeSourceId" @click="getPreview">Preview merge</button><div v-if="preview"><p>{{ preview.favorite_count }} favorites; {{ preview.duplicate_favorite_count }} duplicates; {{ preview.duplicate_link_ids.length }} duplicate links.</p><p v-if="preview.link_conflicts.length || preview.artwork_conflict" class="form-error">Conflicts need an explicit choice.</p><button class="danger-button" @click="applyMerge">Apply merge</button></div></section></template>
