<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { ApiError, apiRequest } from "../../api"

type Alias = { id: number; alias: string; normalized_alias: string }
type Profile = { id: number; display_name: string; normalized_name: string; description: string | null; model_count: number; aliases: Alias[] }
type Preview = { favorite_count: number; duplicate_favorite_count: number; duplicate_link_ids: number[]; link_conflicts: Array<{ source_link_id: number; label: string }>; artwork_conflict: boolean }
const profiles = ref<Profile[]>([]); const selectedId = ref<number | null>(null); const name = ref(""); const description = ref(""); const alias = ref(""); const mergeSourceId = ref<number | null>(null); const preview = ref<Preview | null>(null); const error = ref("")
const selected = computed(() => profiles.value.find(p => p.id === selectedId.value) ?? null)
const candidates = computed(() => profiles.value.filter(p => p.id !== selectedId.value))
function choose(profile: Profile) { selectedId.value = profile.id; name.value = profile.display_name; description.value = profile.description ?? ""; preview.value = null }
async function load() { try { profiles.value = await apiRequest<Profile[]>("/api/admin/creator-profiles") } catch (cause) { error.value = cause instanceof ApiError ? cause.message : "Unable to load creator profiles" } }
async function save() { if (!selected.value) return; try { await apiRequest(`/api/admin/creator-profiles/${selected.value.id}`, { method: "PUT", body: JSON.stringify({ display_name: name.value, description: description.value || null }) }); await load() } catch (cause) { error.value = cause instanceof ApiError ? cause.message : "Unable to save profile" } }
async function addAlias() { if (!selected.value || !alias.value.trim()) return; try { await apiRequest(`/api/admin/creator-profiles/${selected.value.id}/aliases`, { method: "POST", body: JSON.stringify({ alias: alias.value }) }); alias.value = ""; await load() } catch (cause) { error.value = cause instanceof ApiError ? cause.message : "Unable to add alias" } }
async function removeAlias(item: Alias) { if (!selected.value) return; await apiRequest(`/api/admin/creator-profiles/${selected.value.id}/aliases/${item.id}`, { method: "DELETE" }); await load() }
async function getPreview() { if (!selected.value || !mergeSourceId.value) return; preview.value = await apiRequest<Preview>("/api/admin/creator-profiles/merge/preview", { method: "POST", body: JSON.stringify({ target_profile_id: selected.value.id, source_profile_ids: [mergeSourceId.value] }) }) }
async function applyMerge() { if (!selected.value || !mergeSourceId.value || !preview.value) return; const artwork = preview.value.artwork_conflict ? prompt(`Artwork: target or source:${mergeSourceId.value}`, "target") : null; if (preview.value.artwork_conflict && artwork !== "target" && artwork !== `source:${mergeSourceId.value}`) return; const link_resolutions = preview.value.link_conflicts.map(conflict => ({ source_link_id: conflict.source_link_id, action: confirm(`Keep source link ${conflict.label}?`) ? "keep_source" : "keep_target" })); await apiRequest("/api/admin/creator-profiles/merge", { method: "POST", body: JSON.stringify({ target_profile_id: selected.value.id, source_profile_ids: [mergeSourceId.value], artwork_resolution: artwork, link_resolutions }) }); await load(); preview.value = null }
onMounted(() => void load())
</script>
<template><section class="creator-profile-management"><h2>Creator profiles</h2><p v-if="error" class="form-error">{{ error }}</p><div class="admin-grid"><aside><button v-for="profile in profiles" :key="profile.id" class="creator-profile-choice" @click="choose(profile)">{{ profile.display_name }} <small>{{ profile.model_count }} models</small></button></aside><section v-if="selected"><h3>Profile</h3><form class="source-form" @submit.prevent="save"><label>Display name<input v-model="name" required></label><label>Description<textarea v-model="description" /></label><button class="primary-button">Save profile</button></form><h3>Aliases</h3><ul><li v-for="item in selected.aliases" :key="item.id">{{ item.alias }} <button v-if="item.normalized_alias !== selected.normalized_name" class="text-button" @click="removeAlias(item)">Remove</button></li></ul><form @submit.prevent="addAlias"><input v-model="alias" placeholder="Add alias"><button>Add alias</button></form><h3>Merge</h3><select v-model.number="mergeSourceId"><option :value="null">Choose source profile</option><option v-for="profile in candidates" :key="profile.id" :value="profile.id">{{ profile.display_name }}</option></select><button :disabled="!mergeSourceId" @click="getPreview">Preview merge</button><div v-if="preview"><p>{{ preview.favorite_count }} favorites; {{ preview.duplicate_favorite_count }} duplicates; {{ preview.duplicate_link_ids.length }} duplicate links.</p><p v-if="preview.link_conflicts.length || preview.artwork_conflict" class="form-error">Conflicts need an explicit choice.</p><button class="danger-button" @click="applyMerge">Apply merge</button></div></section></div></section></template>
