<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { ApiError, apiRequest } from "../../api"
import AdminHeader from "../../components/AdminHeader.vue"
type Alias = { id:number; alias:string; normalized_alias:string }
type Profile = { id:number; display_name:string; normalized_name:string; description:string|null; model_count:number; aliases:Alias[] }
type Preview = { favorite_count:number; duplicate_favorite_count:number; duplicate_link_ids:number[]; link_conflicts:Array<{source_link_id:number; label:string}>; artwork_conflict:boolean }
const profiles=ref<Profile[]>([]), selectedId=ref<number|null>(null), name=ref(""), description=ref(""), alias=ref(""), mergeSourceId=ref<number|null>(null), preview=ref<Preview|null>(null), error=ref(""), success=ref("")
const selected=computed(()=>profiles.value.find(p=>p.id===selectedId.value)??null); const candidates=computed(()=>profiles.value.filter(p=>p.id!==selectedId.value))
function choose(p:Profile){selectedId.value=p.id;name.value=p.display_name;description.value=p.description??"";alias.value="";preview.value=null}
async function load(){try{profiles.value=await apiRequest<Profile[]>("/api/admin/creator-profiles");const p=profiles.value.find(x=>x.id===selectedId.value);if(p)choose(p)}catch(e){error.value=e instanceof ApiError?e.message:"Unable to load creator profiles"}}
async function save(){if(!selected.value)return;try{const p=await apiRequest<Profile>(`/api/admin/creator-profiles/${selected.value.id}`,{method:"PUT",body:JSON.stringify({display_name:name.value,description:description.value||null})});await load();choose(p);success.value="Creator profile saved."}catch(e){error.value=e instanceof ApiError?e.message:"Unable to save profile"}}
async function addAlias(){if(!selected.value||!alias.value.trim())return;try{await apiRequest(`/api/admin/creator-profiles/${selected.value.id}/aliases`,{method:"POST",body:JSON.stringify({alias:alias.value})});alias.value="";await load()}catch(e){error.value=e instanceof ApiError?e.message:"Unable to add alias"}}
async function removeAlias(a:Alias){if(!selected.value||!confirm(`Remove alias ${a.alias}?`))return;try{await apiRequest(`/api/admin/creator-profiles/${selected.value.id}/aliases/${a.id}`,{method:"DELETE"});await load()}catch(e){error.value=e instanceof ApiError?e.message:"Unable to remove alias"}}
async function getPreview(){if(!selected.value||!mergeSourceId.value)return;try{preview.value=await apiRequest<Preview>("/api/admin/creator-profiles/merge/preview",{method:"POST",body:JSON.stringify({target_profile_id:selected.value.id,source_profile_ids:[mergeSourceId.value]})})}catch(e){error.value=e instanceof ApiError?e.message:"Unable to preview merge"}}
async function applyMerge(){if(!selected.value||!preview.value||!mergeSourceId.value)return;const artwork=preview.value.artwork_conflict?prompt(`Artwork conflict: target or source:${mergeSourceId.value}`,"target"):null;if(preview.value.artwork_conflict&&artwork!=="target"&&artwork!==`source:${mergeSourceId.value}`) return;const links=preview.value.link_conflicts.map(x=>({source_link_id:x.source_link_id,action:confirm(`Keep source link for ${x.label}?`) ? "keep_source":"keep_target"}));if(!confirm("Apply this merge? This cannot be undone."))return;try{const p=await apiRequest<Profile>("/api/admin/creator-profiles/merge",{method:"POST",body:JSON.stringify({target_profile_id:selected.value.id,source_profile_ids:[mergeSourceId.value],artwork_resolution:artwork,link_resolutions:links})});await load();choose(p);preview.value=null;mergeSourceId.value=null;success.value="Creator profiles merged."}catch(e){error.value=e instanceof ApiError?e.message:"Merge was not applied"}}
onMounted(()=>void load())
</script>
<template><main class="admin-page"><AdminHeader title="Creator management" description="Manage stable creator profiles, aliases and safe merges. Library files are never changed."/><p v-if="error" class="form-error">{{error}}</p><p v-if="success" class="form-success">{{success}}</p><section class="admin-grid"><aside class="panel"><h2>Creators</h2><button v-for="p in profiles" :key="p.id" class="creator-profile-choice" :class="{active:selectedId===p.id}" @click="choose(p)">{{p.display_name}} <small>{{p.model_count}} models</small></button></aside><section v-if="selected" class="panel"><h2>{{selected.display_name}}</h2><form class="source-form" @submit.prevent="save"><label>Display name<input v-model="name" required maxlength="255"></label><label>Description<textarea v-model="description" rows="4"/></label><button class="primary-button">Save profile</button></form><section><h3>Aliases</h3><p class="muted">Renaming retains the previous name as an alias.</p><ul><li v-for="a in selected.aliases" :key="a.id">{{a.alias}} <button v-if="a.normalized_alias!==selected.normalized_name" class="text-button" @click="removeAlias(a)">Remove</button></li></ul><form class="inline-form" @submit.prevent="addAlias"><input v-model="alias" placeholder="Add alias"><button>Add alias</button></form></section><section><h3>Merge into {{selected.display_name}}</h3><select v-model.number="mergeSourceId"><option :value="null">Choose source profile</option><option v-for="p in candidates" :key="p.id" :value="p.id">{{p.display_name}}</option></select><button :disabled="!mergeSourceId" @click="getPreview">Preview merge</button><div v-if="preview"><p>{{preview.favorite_count}} favorites; {{preview.duplicate_favorite_count}} duplicate favorites; {{preview.duplicate_link_ids.length}} duplicate links.</p><p v-if="preview.link_conflicts.length||preview.artwork_conflict" class="form-error">Conflicts require an explicit choice before apply.</p><button class="danger-button" @click="applyMerge">Apply merge</button></div></section></section><section v-else class="panel"><p class="muted">Select a creator profile to manage it.</p></section></section></main></template>
