<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue"
import { apiRequest } from "../../api"
import AdminHeader from "../../components/AdminHeader.vue"
import TagChip from "../../components/TagChip.vue"
import { useAuthStore } from "../../stores/auth"

interface Tag { id:number; name:string; color:string|null; description:string|null }
interface Source { id:number; name:string }
interface Target { target_type:string; folder_segment:boolean }
interface Rule { id:number; library_source_id:number|null; match_mode:"contains"|"regex"|"path_relation"; pattern:string|null; path_value:string|null; path_relation:"direct_child"|"self_or_descendant"|null; enabled:boolean; targets:Target[]; match_count:number }
interface Preview { model_name:string; relative_path:string }
const auth=useAuthStore()
const canTags=auth.can("tags.manage")
const canRules=auth.can("tag_rules.manage") && Boolean(auth.user?.source_access.all_sources)
const tags=ref<Tag[]>([]), sources=ref<Source[]>([]), selectedId=ref<number|null>(null), rules=ref<Rule[]>([]), busy=ref(false), error=ref(""), feedback=ref(""), preview=ref<Preview[]>([]), editingRule=ref<number|null>(null), editingTag=ref(false)
const selected=computed(()=>tags.value.find(tag=>tag.id===selectedId.value)??null)
const tagForm=reactive({name:"",color:"#5eead4",description:""})
const ruleForm=reactive({match_mode:"contains" as Rule["match_mode"],pattern:"",path_value:"",path_relation:"self_or_descendant",library_source_id:"",enabled:true,targets:["archive_entry_path"] as string[],folder_segment:false})
const textMode=computed(()=>ruleForm.match_mode!=="path_relation")
function message(value:string){feedback.value=value;error.value=""}
function select(id:number){selectedId.value=id; editingTag.value=false; preview.value=[]; loadRules()}
async function loadRules(){rules.value=canRules&&selectedId.value?await apiRequest<Rule[]>(`/api/admin/tags/${selectedId.value}/assignment-rules`):[]}
async function load(){tags.value=await apiRequest<Tag[]>("/api/admin/tags");if(!selected.value)selectedId.value=tags.value[0]?.id??null;if(canRules)sources.value=await apiRequest<Source[]>("/api/admin/tags/library-sources");await loadRules()}
function startTagEdit(){if(!selected.value)return;Object.assign(tagForm,selected.value);editingTag.value=true}
function resetRule(){Object.assign(ruleForm,{match_mode:"contains",pattern:"",path_value:"",path_relation:"self_or_descendant",library_source_id:"",enabled:true,targets:["archive_entry_path"],folder_segment:false});editingRule.value=null;preview.value=[]}
function rulePayload(){return ruleForm.match_mode==="path_relation"?{match_mode:"path_relation",path_value:ruleForm.path_value,path_relation:ruleForm.path_relation,library_source_id:ruleForm.library_source_id?Number(ruleForm.library_source_id):null,enabled:ruleForm.enabled,targets:[{target_type:"model_relative_path",folder_segment:false}]}:{match_mode:ruleForm.match_mode,pattern:ruleForm.pattern,library_source_id:ruleForm.library_source_id?Number(ruleForm.library_source_id):null,enabled:ruleForm.enabled,targets:ruleForm.targets.map(target_type=>({target_type,folder_segment:target_type==="model_relative_path"&&ruleForm.folder_segment}))}}
async function saveTag(){if(!canTags)return;busy.value=true;try{const method=editingTag.value?"PUT":"POST";const url=editingTag.value?`/api/admin/tags/${selectedId.value}`:"/api/admin/tags";const saved=await apiRequest<Tag>(url,{method,body:JSON.stringify({...tagForm,description:tagForm.description||null})});editingTag.value=false;if(method==="POST")selectedId.value=saved.id;await load();message(`Tag ${method==="POST"?"created":"updated"}.`)}catch(e){error.value=e instanceof Error?e.message:"Unable to save tag"}finally{busy.value=false}}
async function deleteTag(){if(!selected.value||!confirm(`Delete ${selected.value.name}?`))return;await apiRequest(`/api/admin/tags/${selected.value.id}`,{method:"DELETE"});selectedId.value=null;await load();message("Tag deleted.")}
async function saveRule(){if(!selectedId.value)return;busy.value=true;try{const url=editingRule.value?`/api/admin/tag-assignment-rules/${editingRule.value}`:`/api/admin/tags/${selectedId.value}/assignment-rules`;await apiRequest(url,{method:editingRule.value?"PUT":"POST",body:JSON.stringify(rulePayload())});resetRule();await loadRules();message("Assignment rule saved.")}catch(e){error.value=e instanceof Error?e.message:"Unable to save assignment rule"}finally{busy.value=false}}
async function previewRule(){busy.value=true;try{preview.value=await apiRequest<Preview[]>("/api/admin/tag-assignment-rules/preview",{method:"POST",body:JSON.stringify({...rulePayload(),limit:25})})}catch(e){error.value=e instanceof Error?e.message:"Unable to preview rule"}finally{busy.value=false}}
function editRule(rule:Rule){editingRule.value=rule.id;Object.assign(ruleForm,{match_mode:rule.match_mode,pattern:rule.pattern??"",path_value:rule.path_value??"",path_relation:rule.path_relation??"self_or_descendant",library_source_id:rule.library_source_id?String(rule.library_source_id):"",enabled:rule.enabled,targets:rule.targets.map(t=>t.target_type),folder_segment:rule.targets.some(t=>t.target_type==="model_relative_path"&&t.folder_segment)})}
async function removeRule(rule:Rule){if(!confirm("Delete this assignment rule?"))return;await apiRequest(`/api/admin/tag-assignment-rules/${rule.id}`,{method:"DELETE"});await loadRules();message("Assignment rule deleted.")}
async function reevaluate(rule:Rule){busy.value=true;try{await apiRequest(`/api/admin/tag-assignment-rules/${rule.id}/re-evaluate`,{method:"POST"});await loadRules();message("Assignment rule re-evaluated.")}finally{busy.value=false}}
watch(()=>ruleForm.match_mode,()=>{if(ruleForm.match_mode==="path_relation")ruleForm.targets=["model_relative_path"]});onMounted(load)
</script>
<template>
<main class="admin-shell"><AdminHeader title="Tags"/><p v-if="error" class="form-error">{{error}}</p><p v-if="feedback" class="success-panel">{{feedback}}</p>
<section class="layout"><aside class="panel"><h2>Tags</h2><button v-for="tag in tags" :key="tag.id" class="tag-select" :class="{selected:tag.id===selectedId}" @click="select(tag.id)"><TagChip :color="tag.color" :description="tag.description">{{tag.name}}</TagChip></button><p v-if="!tags.length" class="panel-copy">No tags yet.</p></aside>
<section class="panel"><template v-if="selected"><header class="panel-heading"><div><h2>{{selected.name}}</h2><p class="panel-copy">{{selected.description||"Manage this tag."}}</p></div><div v-if="canTags" class="row-actions"><button class="secondary-button" @click="startTagEdit">Edit tag</button><button class="danger-button" @click="deleteTag">Delete tag</button></div></header>
<form v-if="canTags" class="tag-form" @submit.prevent="saveTag"><h3>{{editingTag?"Edit tag":"Create tag"}}</h3><label><span>Name</span><input v-model="tagForm.name" required maxlength="80"></label><label><span>Colour</span><input v-model="tagForm.color" type="color"></label><label><span>Description</span><textarea v-model="tagForm.description" maxlength="1000"></textarea></label><div class="row-actions"><button class="primary-button" :disabled="busy">{{editingTag?"Save tag":"Create tag"}}</button><button v-if="editingTag" type="button" class="secondary-button" @click="editingTag=false">Cancel</button></div></form>
<template v-if="canRules"><h3>Assignment rules</h3><form class="rule-form" @submit.prevent="saveRule"><label><span>Match mode</span><select v-model="ruleForm.match_mode"><option value="contains">Text contains</option><option value="regex">Regular expression</option><option value="path_relation">Folder path</option></select></label><label><span>Source scope</span><select v-model="ruleForm.library_source_id"><option value="">All sources</option><option v-for="source in sources" :key="source.id" :value="String(source.id)">{{source.name}}</option></select></label><label v-if="textMode"><span>{{ruleForm.match_mode==='regex'?'Regular expression':'Text to match'}}</span><input v-model="ruleForm.pattern" required placeholder="(_P|P\.)[2-9]"></label><label v-else><span>Folder path</span><input v-model="ruleForm.path_value" required></label><label v-if="!textMode"><span>Include</span><select v-model="ruleForm.path_relation"><option value="self_or_descendant">Folder and subfolders</option><option value="direct_child">Direct children only</option></select></label><fieldset v-if="textMode"><legend>Search targets</legend><label v-for="target in ['model_relative_path','archive_filename','archive_entry_path','archive_entry_name']" :key="target"><input v-model="ruleForm.targets" type="checkbox" :value="target"> {{target.replaceAll('_',' ')}}</label><label v-if="ruleForm.targets.includes('model_relative_path')"><input v-model="ruleForm.folder_segment" type="checkbox"> Match individual folder names</label></fieldset><label><input v-model="ruleForm.enabled" type="checkbox"> Enabled</label><div class="row-actions"><button class="primary-button" :disabled="busy">{{editingRule?'Save rule':'Add rule'}}</button><button v-if="textMode" type="button" class="secondary-button" @click="previewRule">Preview</button><button v-if="editingRule" type="button" class="secondary-button" @click="resetRule">Cancel</button></div></form><div v-if="preview.length" class="preview"><strong>Preview matches</strong><p v-for="model in preview" :key="model.relative_path">{{model.model_name}} · {{model.relative_path}}</p></div><article v-for="rule in rules" :key="rule.id" class="rule"><div><b>{{rule.match_mode}}</b> · {{rule.match_count}} matches · {{rule.enabled?'Enabled':'Disabled'}}</div><div class="row-actions"><button class="secondary-button" @click="editRule(rule)">Edit</button><button class="secondary-button" @click="reevaluate(rule)">Re-evaluate rule</button><button class="danger-button" @click="removeRule(rule)">Delete</button></div></article></template><p v-else class="panel-copy">Assignment rules are unavailable for this account.</p></template><template v-else><template v-if="canTags"><h2>Create tag</h2><form class="tag-form" @submit.prevent="saveTag"><label><span>Name</span><input v-model="tagForm.name" required></label><button class="primary-button">Create tag</button></form></template><p v-else class="panel-copy">No tags available.</p></template></section></section></main>
</template>
<style scoped>.layout{display:grid;grid-template-columns:minmax(14rem,.7fr) minmax(0,2fr);gap:1rem}.tag-select{display:block;width:100%;text-align:left;padding:.6rem;margin:.3rem 0;border:1px solid var(--border-color);background:var(--panel-background)}.tag-select.selected{outline:2px solid var(--accent-color)}.tag-form,.rule-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem;margin:1rem 0}.tag-form label,.rule-form label{display:grid;gap:.25rem}.tag-form label:last-of-type,.rule-form fieldset,.rule-form .row-actions{grid-column:1/-1}.rule{display:flex;justify-content:space-between;gap:1rem;padding:.75rem;border:1px solid var(--border-color);margin:.5rem 0}.preview{padding:.7rem;background:var(--muted-background)}@media(max-width:760px){.layout,.tag-form,.rule-form{grid-template-columns:1fr}.rule{display:grid}}</style>
