<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue"
import { RouterLink, useRoute } from "vue-router"
import { ApiError, apiRequest } from "../api"
interface CreatorLink { id: number; label: string; url: string }
interface Creator { id: number; display_name: string; description: string | null; model_count: number; artwork: { url: string } | null; links: CreatorLink[] }
interface Model { id: number; name: string; variant: string | null; thumbnail_url: string | null }
interface ModelPage { items: Model[]; total: number; page: number; page_size: number }
const route = useRoute(); const creator = ref<Creator | null>(null); const models = ref<ModelPage | null>(null); const loading = ref(true); const missing = ref(false); const page = ref(1); const id = computed(() => Number(route.params.id))
function safeUrl(value: string): string | null { try { const url = new URL(value); return ["https:", "http:"].includes(url.protocol) ? url.href : null } catch { return null } }
async function load() { loading.value = true; missing.value = false; creator.value = null; models.value = null; try { creator.value = await apiRequest<Creator>(`/api/creators/${id.value}`); models.value = await apiRequest<ModelPage>(`/api/models?creator_profile_id=${id.value}&page=${page.value}&page_size=24&sort=name_asc`) } catch (error) { missing.value = error instanceof ApiError && error.status === 404 } finally { loading.value = false } }
function changePage(next: number) { page.value = next; void load() }
onMounted(() => void load()); watch(() => route.params.id, () => { page.value = 1; void load() })
</script>
<template>
  <main class="creator-page"><p v-if="loading" class="loading-state">Loading creator…</p><section v-else-if="missing" class="empty-state"><h1>Creator not found</h1><p>This creator is unavailable or you do not have access to its models.</p><RouterLink to="/">Back to catalogue</RouterLink></section><p v-else-if="!creator" class="error-message">Unable to load this creator.</p><template v-else><header class="creator-header"><div class="creator-artwork creator-artwork-large"><img v-if="creator.artwork" :src="creator.artwork.url" :alt="`${creator.display_name} artwork`"><span v-else>{{ creator.display_name.slice(0, 1).toUpperCase() }}</span></div><div><p class="eyebrow">Creator</p><h1>{{ creator.display_name }}</h1><p v-if="creator.description" class="creator-description">{{ creator.description }}</p><p class="creator-model-count">{{ creator.model_count }} visible {{ creator.model_count === 1 ? "model" : "models" }}</p><div v-if="creator.links.length" class="creator-links"><a v-for="link in creator.links" :key="link.id" v-show="safeUrl(link.url)" :href="safeUrl(link.url)!" target="_blank" rel="noopener noreferrer">{{ link.label }} ↗</a></div></div></header><section class="creator-models"><h2>Models</h2><p v-if="!models?.items.length">No visible models.</p><div v-else class="creator-model-grid"><RouterLink v-for="model in models.items" :key="model.id" class="creator-model-tile" :to="{ name: 'model-detail', params: { id: model.id } }"><img v-if="model.thumbnail_url" :src="model.thumbnail_url" :alt="model.name"><span v-else class="thumbnail-placeholder">Fallback preview</span><strong>{{ model.name }}</strong><small v-if="model.variant">{{ model.variant }}</small></RouterLink></div><nav v-if="models && models.total > models.page_size" class="creator-pagination"><button :disabled="page === 1" @click="changePage(page - 1)">Previous</button><span>Page {{ page }}</span><button :disabled="page * models.page_size >= models.total" @click="changePage(page + 1)">Next</button></nav></section></template></main>
</template>
